package com.BE.QuitCare.dto;

import com.BE.QuitCare.enums.LeaveStatus;
import lombok.Data;

import java.time.LocalDate;
import java.time.LocalTime;

@Data
public class SessionUserDTO
{
    private LocalDate date;
    private LocalTime start;
    private LocalTime end;
    private String label;
    private boolean available;
    private boolean autoGenerated;
    private LeaveStatus leaveStatus;
}
